# Generated by Django 2.2.6 on 2020-12-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='csvfile',
            field=models.FileField(upload_to=''),
        ),
    ]
